#!/bin/bash

# Expected 'go' binary for the selected go instance is available via PATH environment variable
nohup go run main.go --serve > nohup.log 2>&1
echo $! > nohup.pid

echo "Started Golang background process: $(cat nohup.pid)"